### ISSUE TITLE
Input Key Format

### ISSUE THREAD

**Issue by eduardomcm** [guardicore/iencrypt_decryptor#1]
Would you be able to add the key format to the readme.md file? I am trying this decryptor but the format isn't clear and I keep getting the following error:

CryptImportKey for RSA key failed with error -2146893817: Bad Version of provider.

**Comment by danielguardicore** [comment]
Hey, we just updated the README, take a look and tell us if this is clearer.

**Comment by jj-lehmann** [comment]
Sure, added it.
